// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2bITHcNFi0ic9SbjJdc8OCI-7bvd9S8',
    appId: '1:263499176659:web:c8f35397fb6c4042229226',
    messagingSenderId: '263499176659',
    projectId: 'zerowaste-3934f',
    authDomain: 'zerowaste-3934f.firebaseapp.com',
    storageBucket: 'zerowaste-3934f.appspot.com',
    measurementId: 'G-LZDN7EEY41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSizOxLvffiAXgR14qsj2s9F6OUgErmW0',
    appId: '1:263499176659:android:908ce1cb2c9e980e229226',
    messagingSenderId: '263499176659',
    projectId: 'zerowaste-3934f',
    storageBucket: 'zerowaste-3934f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqAqjlO9AbyPGqcRud2Kj8Mtk5tA9nJSo',
    appId: '1:263499176659:ios:7f95a0767293c0bd229226',
    messagingSenderId: '263499176659',
    projectId: 'zerowaste-3934f',
    storageBucket: 'zerowaste-3934f.appspot.com',
    iosBundleId: 'com.example.zerowaste111',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqAqjlO9AbyPGqcRud2Kj8Mtk5tA9nJSo',
    appId: '1:263499176659:ios:02477a51ad5a47cc229226',
    messagingSenderId: '263499176659',
    projectId: 'zerowaste-3934f',
    storageBucket: 'zerowaste-3934f.appspot.com',
    iosBundleId: 'com.example.zerowaste111.RunnerTests',
  );
}
